EasyFood/EasyFood/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyFood.DAL;
using EasyFood.Models;
using System.Reflection;

namespace EasyFood.Controllers
{
    public class ClientController : Controller
    {
        private EasyFoodContext db = new EasyFoodContext();

        // GET: Client
        public ActionResult Index()
        {
            return View(db.Clienti.ToList());
        }

        public ActionResult Autentificare(string username, string parola)
        {
            Client client;

            if (TempData["IDUtilizator"] == null)
            {
                
                if (username == null || parola == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                IQueryable<EasyFood.Models.Client> clienti =
                                    from cl in db.Clienti
                                    where cl.Email == username && cl.Parola == parola
                                    select cl;

                if (clienti.Count() == 1)
                {
                    client = clienti.Single();
                    TempData["IDUtilizator"] = client.ID;
                    return View(client);
                }
                else
                {
                    return HttpNotFound();
                }
                
            }

            TempData.Keep();

            client = db.Clienti.Find(TempData["IDUtilizator"]);
            TempData.Keep();

            if (client == null)
            {
                return HttpNotFound();
            }
             
            return View(client);
            
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nume,Prenume,Email,DataNasterii,Adresa,Parola,LinkPoza")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clienti.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clienti.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nume,Prenume,Email,DataNasterii,Adresa,Parola,LinkPoza")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { ID = client.ID});
            }
            return View(client);
        }

        // GET: Client/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clienti.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clienti.Find(id);
            db.Clienti.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EasyFood/EasyFood/Controllers/RetetaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyFood.DAL;
using EasyFood.Models;
using EasyFood.ViewModels;
using EasyFood.ServiceReference2;

namespace EasyFood.Controllers
{
    public class RetetaController : Controller
    {

        private EasyFoodContext db = new EasyFoodContext();

        // GET: Reteta
        public ActionResult Index()
        {
            var retete = db.Retete.Include(d => d.Ingrediente);
            return View(retete.ToList());
        }

        // GET: Reteta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reteta reteta = db.Retete.Find(id);
            if (reteta == null)
            {
                return HttpNotFound();
            }
           
            ValoareNutritionalaReteta vnr = new ValoareNutritionalaReteta(reteta);
            return View(vnr);
        }

        // GET: Reteta/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reteta/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RetetaID,Denumire,Descriere,Stoc,Pret,LinkImaginePrezentare,NivelDificultate,TimpPreparare,Categorie,LinkVideo")] Reteta reteta)
        {
            if (ModelState.IsValid)
            {
                db.Retete.Add(reteta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reteta);
        }

        // GET: Reteta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reteta reteta = db.Retete.Find(id);
            if (reteta == null)
            {
                return HttpNotFound();
            }
            return View(reteta);
        }

        // POST: Reteta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RetetaID,Denumire,Descriere,Stoc,Pret,LinkImaginePrezentare,NivelDificultate,TimpPreparare,Categorie,LinkVideo")] Reteta reteta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reteta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reteta);
        }

        // GET: Reteta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reteta reteta = db.Retete.Find(id);
            if (reteta == null)
            {
                return HttpNotFound();
            }
            return View(reteta);
        }

        // POST: Reteta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reteta reteta = db.Retete.Find(id);
            db.Retete.Remove(reteta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EasyFood/EasyFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Easy Food</title>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="/Styles/EasyFood.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
    .elementlista a:visited
    {
        color: dimgray !important;
    }

    .elementlista a:hover
    {
        color: black !important;
    }

    .logo:hover
    {
        color: black !important;
    }

    .navbar-toggle .icon-bar
    {
        background-color:red;
    }

    </style>
</head>

<body>
    <div class="navbar navbar-fixed-top easyfood-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="continutCentrat" style="padding-top:12px; padding-bottom:3px; padding-right:12px">
                    <p style="font-family: 'Varela Round', sans-serif; font-weight:bold; font-size:20px"><span style="color:red">easy</span><span style="color:#0094ff">food</span><span style="font-size:10px">&reg;</span></p>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="elementlista">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="elementlista">@Html.ActionLink("Retete", "Index", "Reteta")</li>
                    @if(TempData["IDUtilizator"] != null)
                    {
                        TempData.Keep();
                        <li class="elementlista">
                            @Html.ActionLink("Contul Meu", "Autentificare", "Client", new {id = TempData["IDUtilizator"]}, null)
                        </li>
                        TempData.Keep();
                    }
                    else
                    {
                        <li class="elementlista">@Html.ActionLink("Contul Meu", "Index", "Client")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Easy Food</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>